theme = "themescactus"
title = "Anabila"

[params]
description = "Aspiring computer engineering researcher with an interest in Hardware Acceleration and Computer Architecture."
colortheme = "dark"
showAllPostsOnHomePage = false
postsOnHomePage = 5

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "Publications"
url = "/publications"
weight = 4

[[menu.main]]
name = "About"
url = "/about"
weight = 5


[[params.social]]
  name = "github"
  link = "https://github.com/anthonyabeo"

[[params.social]]
  name = "email"
  link = "anthonyabeo@gmail.com"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/anthony-abeo-7256b6186/"

[[params.social]]
  name = "twitter"
  link = "https://www.twitter.com/anthonyabeo7"

copyright = "Anthony Abeo"